In [1]:
import numpy as np

In [2]:
kanto =np.array([73,67,43])

In [3]:
kanto

array([73, 67, 43])

In [4]:
weight=np.array([0.1,0.2,0.3])

In [5]:
weight

array([0.1, 0.2, 0.3])

In [6]:
np.dot(kanto,weight)

33.6

In [7]:
help(np.dot)

Help on function dot in module numpy:

dot(...)
    dot(a, b, out=None)
    
    Dot product of two arrays. Specifically,
    
    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).
    
    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.
    
    - If either `a` or `b` is 0-D (scalar), it is equivalent to :func:`multiply`
      and using ``numpy.multiply(a, b)`` or ``a * b`` is preferred.
    
    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.
    
    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of `b`::
    
        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
    
    Parameters
    ----------
    a : array_like
        First argument.
    b : array_like
        Second argument.
    out : 

In [9]:
(kanto*weight).sum()


33.6

In [10]:
kanto.sum()

183

In [11]:
weight.sum()

0.6000000000000001

In [12]:
kanto*weight

array([ 7.3, 13.4, 12.9])

In [13]:
kanto

array([73, 67, 43])

In [35]:
arr1=list(range(1000000))
arr2=list(range(1000000,2000000))
arr1=np.array(arr1)
arr2=np.array(arr2)

In [36]:
%%time
result=0
for x1,x2 in zip(arr1,arr2):
    result +=x1*x2
result

<timed exec>:3: RuntimeWarning: overflow encountered in long_scalars


Wall time: 1.57 s


-1942957984

In [37]:
%%time
(arr1*arr2).sum()

Wall time: 2.02 ms


-1942957984

In [38]:
%%time
np.dot(arr1,arr2)

Wall time: 0 ns


-1942957984

In [46]:
data=np.array([
    [73,34,35],
    [34,56,78],
    [45,67,89],
    [34.4,56,78]
])

In [41]:
data.shape

(4, 3)

In [42]:
data

array([[73, 34, 35],
       [34, 56, 78],
       [45, 67, 89],
       [34, 56, 78]])

In [43]:
data[0][1]

34

In [44]:
data[0].shape

(3,)

In [47]:
data.dtype

dtype('float64')

In [48]:
data

array([[73. , 34. , 35. ],
       [34. , 56. , 78. ],
       [45. , 67. , 89. ],
       [34.4, 56. , 78. ]])

In [50]:
np.matmul(data,weight)

array([24.6 , 38.  , 44.6 , 38.04])

In [51]:
data @ weight

array([24.6 , 38.  , 44.6 , 38.04])

In [53]:
import urllib.request

In [56]:
urllib.request.urlretrieve(
    'https://hub.jovian.ml/wp-content/uploads/2020/08/climate.csv', 
    'climate.txt')


('climate.txt', <http.client.HTTPMessage at 0x263bb0a0d90>)

In [57]:
climate_data=np.genfromtxt('climate.txt',delimiter=',',skip_header=1)

In [58]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [60]:
climate_data.shape

(10000, 3)

In [61]:
yeild=climate_data@weight

In [62]:
yeild

array([47.4, 37.9, 38. , ..., 39.7, 48.5, 39.8])

In [63]:
yeild.shape

(10000,)

In [66]:
climate_results=np.concatenate((climate_data,yeild.reshape(10000,1)),axis=1)

In [67]:
climate_results

array([[25. , 76. , 99. , 47.4],
       [39. , 65. , 70. , 37.9],
       [59. , 45. , 77. , 38. ],
       ...,
       [99. , 62. , 58. , 39.7],
       [70. , 71. , 91. , 48.5],
       [92. , 39. , 76. , 39.8]])

In [68]:
np.savetxt('climate_results.txt',
          climate_results,
          fmt='%.2f',
          header=('temprature,rainfalll,humidity,yield'),
           comments='')

